ad_posts/urls.py
from django.conf.urls import url, include
from ad_posts.views import AdPostsView, AdDetailView, AdCreate, FormAdd


urlpatterns = [
    url(r'^$', AdPostsView.as_view(), name='ad_posts'),
    url(r'^(?P<pk>\d+)/detail/$',AdDetailView.as_view(), name="ad_detail"),
    url(r'^add/$',AdCreate.as_view(), name="ad_add"),
    url(r'^form_special/(?P<pk>\d+)/$', FormAdd.as_view()),

    url(r'^votes/', include('ad_posts.url.votes')),
]

faq/urls.py
from django.conf.urls import url
from faq.views import FaqView


urlpatterns = [
    url(r'^$', FaqView.as_view(), name='faq'),
]

skill/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include ('main.urls')),

    url(r'^users/', include('users.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^countries/', include('countries.urls')),
    url(r'^regions/', include('regions.urls')),
    url(r'^cities/', include('cities.urls')),
    url(r'^stat/', include('stst.urls')),
    url(r'^manage/', include('logs.urls')),

    url(r'^categories/', include('ad_categories.urls')),
    url(r'^posts/', include('ad_posts.urls')),

    url(r'^skill_categories/', include('skill_categories.urls')),
    url(r'^skill_posts/', include('skill_posts.urls')),

    url(r'^love_posts/', include('love_posts.urls')),

    url(r'^logout/$', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='logout'),
    url(r'^signup/$', TemplateView.as_view(template_name="account/signup.html"), name='signup'),
    url(r'^login/$', TemplateView.as_view(template_name="account/login.html"), name='login'),
    url(r'^email-verification/$', TemplateView.as_view(template_name="account/email_verification.html"), name='email-verification'),
    url(r'^password-reset/$', TemplateView.as_view(template_name="account/password_reset.html"), name='password-reset'),
    url(r'^password-reset/confirm/$', TemplateView.as_view(template_name="account/password_reset_confirm.html"), name='password-reset-confirm'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', TemplateView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    url(r'^password-change/$', TemplateView.as_view(template_name="account/password_change.html"), name='password-change'),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^account/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ad_posts/models.py
from django.db import models
import uuid
from cities.models import City
from django.conf import settings
from django.contrib.postgres.indexes import BrinIndex
from pilkit.processors import ResizeToFill, ResizeToFit
from imagekit.models import ProcessedImageField
from ad_posts.helpers import upload_to_user_directory


class Ad(models.Model):
    id = models.BigIntegerField(unique=True, primary_key=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="uuid")
    title = models.CharField(max_length=200, verbose_name="Название")
    description = models.TextField(max_length=1000, verbose_name="Описание товара")
    price = models.PositiveIntegerField(default=0, verbose_name="Цена товара")
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Пользователь")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="Город")
    category = models.ForeignKey('ad_categories.AdSubCategory', on_delete=models.CASCADE, verbose_name="Ккатегория")
    is_active = models.BooleanField(default=False, verbose_name='Объявление опубликовано')
    is_deleted = models.BooleanField(default=False, verbose_name='Объявление удалено')
    is_sold = models.BooleanField(default=False, verbose_name='Объявление не актуально')
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Время публикации")
    is_reklama = models.BooleanField(default=False, verbose_name='Это реклама')
    votes_off = models.BooleanField(default=False, verbose_name='отключить лайки/дизлайки')

    image = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])
    img1 = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])
    img2 = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])
    img3 = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])
    img4 = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])
    img5 = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])
    img6 = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])
    img7 = ProcessedImageField(format='JPEG', blank=True, options={'quality': 90}, upload_to=upload_to_user_directory, processors=[ResizeToFit(width=1024, upscale=False)])

    def __str__(self):
        return self.title

    class Meta:
        indexes = (BrinIndex(fields=['created']),)
        verbose_name = "Объявление"
        verbose_name_plural = "Объявления"
        ordering=["-created"]

    def all_visits_count(self):
        from stst.models import AdNumbers

        return AdNumbers.objects.filter(ad=self.pk).values('pk').count()

    def likes(self):
        from common.model.votes import AdVotes
        likes = AdVotes.objects.filter(parent=self, vote__gt=0)
        return likes

    def likes_count(self):
        from common.model.votes import AdVotes
        likes = AdVotes.objects.filter(parent=self, vote__gt=0).values("pk")
        return likes.count()

    def dislikes(self):
        from common.model.votes import AdVotes
        dislikes = AdVotes.objects.filter(parent=self, vote__lt=0)
        return dislikes

    def dislikes_count(self):
        from common.model.votes import AdVotes
        dislikes = AdVotes.objects.filter(parent=self, vote__lt=0).values("pk")
        return dislikes.count()


class AdDesign(models.Model):
    ad = models.OneToOneField(Ad, db_index=False, on_delete=models.CASCADE, verbose_name="Объявление")
    color = models.CharField(max_length=10, verbose_name="Цвет текста")
    background = models.CharField(max_length=10, verbose_name="Цвет фона")


class AdFavourites(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE, verbose_name="Объявление")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='ad_favorites', on_delete=models.CASCADE, verbose_name="Пользователь")
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Дата добавления")

    def __str__(self):
        return self.ad.title

    class Meta:
        verbose_name = "Избранное объявление"
        verbose_name_plural = "Избранные объявления"
        unique_together = ('ad', 'user',)
        indexes = (BrinIndex(fields=['created']),)

ad_posts/forms.py
from django import forms


class Form_1(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.auto import Auto
		model=Auto
		exclude = ['creator',]


class Form_2(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.spez_moto import SpecMoto
		model=SpecMoto
		exclude = ['creator',]


class Form_3(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.zap_auto import ZapAuto
		model=ZapAuto
		exclude = ['creator',]


class Form_4(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.realty import Realty
		model=Realty
		exclude = ['creator',]

class Form_5(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.service import Service
		model=Service
		exclude = ['creator',]

class Form_6(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.women import Women
		model=Women
		exclude = ['creator',]

class Form_7(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.man import Man
		model=Man
		exclude = ['creator',]

class Form_8(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.child import Child
		model=Child
		exclude = ['creator',]

class Form_9(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.baby import Baby
		model=Baby
		exclude = ['creator',]

class Form_10(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_posts.models import Ad
		model=Ad
		exclude = ['creator',]

class Form_11(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.phone import PhoneAd
		model=PhoneAd
		exclude = ['creator',]

class Form_12(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.foto_video import FotoVideo
		model=FotoVideo
		exclude = ['creator',]

class Form_13(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.comp import Comp
		model=Comp
		exclude = ['creator',]

class Form_14(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.tv import TV
		model=TV
		exclude = ['creator',]

class Form_15(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.home_tech import HomeTech
		model=HomeTech
		exclude = ['creator',]

class Form_16(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.home_garden import HomeGarden
		model=HomeGarden
		exclude = ['creator',]

class Form_17(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.repair import Repair
		model=Repair
		exclude = ['creator',]

class Form_18(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.beauty import Beauty
		model=Beauty
		exclude = ['creator',]

class Form_19(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.sport import Sport
		model=Sport
		exclude = ['creator',]

class Form_20(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.hobbies import Hobbies
		model=Hobbies
		exclude = ['creator',]

class Form_21(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.job import Job
		model=Job
		exclude = ['creator',]

class Form_22(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.pets import Pets
		model=Pets
		exclude = ['creator',]

class Form_23(forms.ModelForm):
	description = forms.CharField( label="",widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

	class Meta:
		from ad_model.biznes import Biznes
		model=Biznes
		exclude = ['creator',]

ad_posts/views.py
from django.views.generic.base import TemplateView
from ad_posts.models import Ad
from regions.models import Region
from ad_categories.models import AdCategory, AdSubCategory
from django.http import HttpResponse
from common.utils import get_current_form
from ad_posts.forms import Form_1


class AdPostsView(TemplateView):
    template_name = "ad_posts.html"


class AdDetailView(TemplateView):
    template_name = None

    def get(self,request,*args,**kwargs):
        from common.get_templates import get_template_ad_detail

        self.ad = Ad.objects.get(pk=self.kwargs["pk"])
        self.template_name = get_template_ad_detail(ad=self.ad, folder="detail/", template="_cat.html", request=request)
        return super(AdDetailView,self).get(request,*args,**kwargs)

    def get_context_data(self, **kwargs):
        context = super(AdDetailView, self).get_context_data(**kwargs)
        context['ad'] = self.ad
        return context


class AdCreate(TemplateView):
    template_name="ad_add.html"

    def get_context_data(self,**kwargs):
        context=super(AdCreate,self).get_context_data(**kwargs)
        context['ad_categories'] = AdCategory.objects.only("pk")
        context['regions'] = Region.objects.only("pk")
        return context


class FormAdd(TemplateView):
    template_name = None

    def get(self,request,*args,**kwargs):
        self.subcat = AdSubCategory.objects.get(pk=self.kwargs["pk"])
        self.template_name = "forms/cat_" + str(self.subcat.category.order) + "/sub_" + str(self.subcat.order) + ".html"
        return super(FormAdd,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context = super(FormAdd,self).get_context_data(**kwargs)
        context["form"] = get_current_form(self.subcat.order)
        return context

    def post(self,request,*args,**kwargs):
        self.form = get_current_form(self.subcat.order)
        if self.form.is_valid():
            ad = self.form.save(commit=False)
            ad.creator = self.request.user
            ad = self.form.save()
            return HttpResponse ('')
        return super(FormAdd,self).get(request,*args,**kwargs)

ad_posts/templates/ad_add.html
{% extends "bases/base.html" %}
{% load humanize %}
{% block title %}Создание объявления{% endblock %}
{% block content %}

<section id="sect" class="content">
    <section class="block">
      <div class="page-title">
          <div class="container">
              <h1 style="padding-bottom: 7rem;">Добавление объявления</h1>
          </div>
      </div>
        <div class="container" id="testt">
            {% if user.is_anonymous %}
            <section>
                <div class="alert alert-warning" role="alert">
                    <h2 class="alert-heading">Здравствуйте, гость!</h2>
                    <p>Для того, чтобы добавлять объявления, нужно
                        <a href="{% url 'login' %}" class="link"><strong>Войти</strong></a> или
                        <a href="{% url 'register' %}" class="link"><strong>Зарегистрироваться</strong></a></p>
                </div>
            </section>
            {% else %}
            <form class="form form-submit" action="" id="FORM" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <section>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="type" class="required">Категория</label>
                                <select onchange="SelectSubCategory (this)">
                                    <option value="">Выберите категорию</option>
                                    {% for object in ad_categories %}
                                    <option value="{{ object.order }}">{{ object.name_ru }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group subcat" style="display:none">
                            <label for="type" class="required">Подкатегория</label>
                            <select onchange="loadAddForm (this)" name="category" id="id_category">
                              <option value="">Подкатегория</option>
                            </select>
                          </div>
                        </div>
                    </div>
                </section>
                <div class="top_form" style="display:none">
                  {% include 'form_top.html' %}
                </div>
                <div class="special_block"></div>
                <div class="bottom_form" style="display:none">
                  {% include 'form_bottom.html' %}
                </div>
            </form>
            {% endif %}
        </div>
    </section>
</section>

{% endblock %}

ad_posts/templates/form_bottom.html
<section>
    <h2>Добавьте изображения</h2>
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="id_image">
          <input type="file" name="image" accept="image/*" id="id_image">
        </div>
        <div id="image-holder">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 1</h4>
          <p>Главное изображение</p>

          <i style="color:#CECECE">(необязательно)</i>

        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12" style="display:none">
        <div class="id_img1"><input type="file" name="img1" accept="image/*" id="id_img1"></div>
        <div id="image-holder1">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 2</h4>

          <p>Доп. изображение</p>

          <i style="color:#CECECE">(необязательно)</i>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12" style="display:none">
        <div class="id_img2"><input type="file" name="img2" accept="image/*" id="id_img2"></div>
        <div id="image-holder2">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 3</h4>

          <p>Доп. изображение</p>

          <i style="color:#CECECE">(необязательно)</i>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12" style="display:none">
        <div class="id_img3"><input type="file" name="img3" accept="image/*" id="id_img3"></div>
        <div id="image-holder3">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 4</h4>

          <p>Доп. изображение</p>

          <i style="color:#CECECE">(необязательно)</i>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12" style="display:none">
        <div class="id_img4"><input type="file" name="img4" accept="image/*" id="id_img4"></div>
        <div id="image-holder4">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 5</h4>

          <p>Доп. изображение</p>

          <i style="color:#CECECE">(необязательно)</i>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12" style="display:none">
        <div class="id_img5"><input type="file" name="img5" accept="image/*" id="id_img5"></div>
        <div id="image-holder5">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 6</h4>

          <p>Доп. изображение</p>

          <i style="color:#CECECE">(необязательно)</i>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12" style="display:none">
        <div class="id_img6"><input type="file" name="img6" accept="image/*" id="id_img6"></div>
        <div id="image-holder6">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 7</h4>

          <p>Доп. изображение</p>

          <i style="color:#CECECE">(необязательно)</i>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12" style="display:none">
        <div class="id_img7"><input type="file" name="img7" accept="image/*" id="id_img7"></div>
        <div id="image-holder7">
          <h4 style="font-weight:bold;font-size:70px;color:#CECECE">№ 8</h4>

          <p>Доп. изображение</p>

          <i style="color:#CECECE">(необязательно)</i>
        </div>
      </div>
    </div>
</section>

<section class="clearfix" style="margin-left: 20px;">
  <div class="row">
    <ul class="list-unstyled columns-1">
      <li>
        <label class="" style="font-size:15px">
          {{ form.votes_off }}
          {{ form.votes_off.label }}
        </label>
      </li>
    </ul>
  </div>
</section>

<section class="clearfix">
    <div class="form-group">
        <button type="submit" id="create_post" class="btn btn-primary large icon float-right">
          Опубликовать
        </button>
    </div>
</section>

ad_posts/templates/form_top.html
<section>
    <h2>Основная информация</h2>

    <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <label for="type" class="required">Название товара</label>
            <input type="text" name="title" id="id_title" required="" maxlength="200">
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label for="type" class="required">Цена товара</label>
              <input type="number" name="price" value="" min="0" id="id_price" required="">
              <span class="input-group-addon">₽</span>
          </div>
        </div>
    </div>
</section>

  <section>
    <div class="form-group">
    <label>Описание товара</label>
      <textarea name="description" class="form-control" cols="40" rows="5" id="id_description" required=""></textarea>
    </div>
  </section>

  <div class="location_block">
    <section>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
              <label for="type" class="required">Регион</label>
              <select onchange="loadCitySelect (this)" name="region" id="id_region">
                  <option value="">Выберите регион</option>
                  {% for object in regions %}
                  <option value="{{ object.order }}">{{ object.name_ru }}</option>
                  {% endfor %}
              </select>
            </div>
        </div>
        <div class="col-md-6">
          <div class="form-group city" style="display:none">
            <label for="type" class="required">Город</label>
            <select name="city" id="id_city">
            </select>
          </div>
        </div>
    </div>
    </section>
  </div>

ad_posts/templates/section_author.html
{% load humanize %}
<style>
  .img_author img{
    width: 95%;
    height: 95%;
  }
</style>
<section id="creator_pk" data-pk="{{ ad.creator.pk }}">
    <h2>Автор</h2>
    <div class="box">
        <div class="row">
            <div class="col-md-5 img_author">
              <a href="{% url 'user' pk=ad.creator.pk %}" class="image-wrapper background-image ajax">
                {% if ad.creator.avatar %}
                  {{ ad.creator.avatar.url }}
                {% else %}
                  <svg fill="currentColor" class="svg_default" viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/><path d="M0 0h24v24H0z" fill="none"/></svg>
                {% endif %}
              </a>
            </div>

            <div class="col-md-7">
              <div class="author-description">
                <a href="{% url 'user' pk=ad.creator.pk %}" class="text-uppercase ajax">
                  <h3>{{ ad.creator.get_full_name }}</h3>
                </a>

                <hr>
                <dl>
                  <dt>Активность</dt>
                  <dd>{% if ad.creator.get_online %}Онлайн {% else %} Был {{ ad.creator.last_activity }}{% endif %}</dd>
                  <dt>Регион</dt>
                  <dd> {{ ad.creator.get_last_location.region_ru }}</dd>
                  <dt>Город</dt>
                  <dd> {{ ad.creator.get_last_location.city_ru }}</dd>
                  <dt>Телефон</dt>
                  <dd> {{ ad.creator.phone }}</dd>
                </dl>
              </div>
            </div>
        </div>
    </div>
</section>

ad_posts/templates/section_simular.html
{% load humanize %}

{% if ad.get_simular %}
  <section>
      <h2>Похожее</h2>
      <div class="items">
        {% for object in ad.get_simular %}
          <div class="item">
              <div class="ribbon-featured">Похожее</div>
              <div class="wrapper">
                  <div class="image">
                      <h3>
                          <a href="{% url 'ad_detail' pk=object.pk %}" class="title ajax">{{ object.title }}</a>
                          <span class="tag">
                            <i class="fa fa-eye"></i> 0
                            | <i class="fa fa-heart"></i> 0
                          </span>
                      </h3>
                      <a href="{% url 'ad_detail' pk=object.pk %}" class="image-wrapper background-image ajax">
                        {% if object.images %}
                          <img src="{{ object.images.url }}" alt="">
                        {% else %}
                          <img src="/static/images/no_img.jpg" alt="">
                        {% endif %}
                      </a>
                  </div>
                  <h4 class="location">
                      <a href="{% url 'region' region_name=object.city.region.name_en %}" class="ajax">{{ object.city.region }}</a>,
                      <a href="{% url 'city' city_name=object.city.name_en %}" class="ajax">{{ object.city }}</a>
                  </h4>
                  <div class="price rubl">&#8399; {{ object.price|intcomma }}</div>
                  <div class="meta">
                        <figure>
                            <i class="fa fa-calendar-o"></i>{{ object.created|naturaltime }}
                        </figure>
                        <br>
                        <figure>
                            <a href="{% url 'user' pk=object.creator.pk %}" class="ajax">
                                {{ object.creator.get_full_name }}
                            </a>
                        </figure>
                    </div>
                  <div class="description">
                  </div>
                  <div class="additional-info">
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
  </section>
  {% endif %}